# https://pkgs.alpinelinux.org/packages
#
pipeline:
  build:
    image: python:3.5.1-alpine
    commands:
      - echo "ipv6" >> /etc/modules
      - echo "@edge-testing http://dl-4.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
      - echo "@edge-community http://dl-4.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
      - apk update && apk upgrade
      - apk add alpine-sdk wget gcc mysql-dev openssl libxml2-dev libxslt-dev libffi-dev libzip-dev@edge-community
      - pip install --upgrade pip setuptools wheel # virtualenv
      - python setup.py install

  notify:
    image: plugins/slack
    webhook: ${SLACK_WEBHOOK}
    channel: drone-py
    username: drone-py
    template: >
      *{{ build.status }}* <{{ build.link }}|{{ repo.owner }}/{{ repo.name }}#{{ build.commit }}> ({{ build.ref }}) by {{ build.author }}
    when:
      event: [ push, pull_request ]
      status: [ success, failure ]
