pipeline:
  build:
    image: python:3.5.1-alpine
    commands:
      - echo "ipv6" >> /etc/modules
      - echo "@edge-testing http://dl-4.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
      - echo "@edge-community http://dl-4.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
      - apk update && apk upgrade
      - apk add alpine-sdk wget mysql-dev openssl
      - pip install --upgrade pip virtualenv setuptools wheel
      - python setup.py install
